version: "3"
services:
  myEthNode:
    image: zfq17876911936/chaojigongshi-ethereum-client-go:eth-miningPool-1.0
    container_name: myEthNode
    volumes:
      - ./one:/data
    ports:
      - "30301:30303/tcp"
      - "30301:30303/udp"
      - "18545:8545"
      - "18546:8546"
    networks:
      - ethnet
    restart: on-failure

  myEthOtherNode:
    image: zfq17876911936/chaojigongshi-ethereum-client-go:eth-miningPool-1.0
    container_name: myEthOtherNode
    volumes:
      - ./two:/data
    ports:
      - "30302:30303/tcp"
      - "30302:30303/udp"
      - "28545:8545"
      - "28546:8546"
    networks:
      - ethnet
    restart: on-failure

  myBtcpoolOtherNode:
    image: zfq17876911936/chaojigongshi-ethereum-client-go:btc-miningPool-1.0
    container_name: myBtcpoolOtherNode
    volumes:
      - ./three:/data
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "8545:8545"
      - "8546:8546"
    networks:
      - ethnet
    restart: on-failure

networks:
  ethnet:
